name: 'Deployment status fetcher'
description: 'Return deployment data for last two deloyments'
inputs:
  token:
    required: true
    type: string
  environment:
    required: true
    type: string
outputs:
  last: # id of output
    description: 'sha or last deploy'
  prev: # id of output
    description: 'sha or previous deploy'
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: echo Hello direct.
      shell: bash
    - run: |
        echo "last=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
        echo "prev=$(date "+%y%m")-$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
      shell: bash
    - run: deno run --allow-all hello.ts
      shell: bash
    - run: goodbye.sh
      shell: bash
